### ISSUE TITLE
Add stylelint

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#10]
We have scss-lint for checking the SCSS, but [Stylelint](http://stylelint.io/) can be used for checking the CSS output. Through different SCSS, compiling of SCSS, and any PostCSS adjustments, we should be able to make any CSS meet the WP standards for CSS.  There's a handy config by @ntwb - https://github.com/ntwb/stylelint-config-wordpress

**Comment by ntwb** [comment]
I'm slowly working through adding and converting common scss-lint rules but there is little to no _official_ WordPress coding standards for SCSS, so they are inheriting _best practices_ and CSS equivalents is the direction I've taken in that regard.

**Comment by GaryJones** [comment]
Note that the repo is now at https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress.

**Comment by craigsimps** [comment]
Stylelint added with commit fcb363e
