### ISSUE TITLE
Add support for HTTPS

### ISSUE THREAD

**Issue by seothemes** [craigsimps/gulp-wp-toolkit#102]
Add support for BrowserSync's HTTPS feature to allow the use of local SSL certificates.

## Expected Behavior

Enable https for localhost development.

## Current Behavior

From my understanding there is currently no way to enable HTTPS.

```js
bs.init({
    proxy: config.server.url,
    online: true,
});
```

## Possible Solution

Add a conditional to check if HTTPS settings have been defined in the config. E.g:

```js
bs.init({
    proxy: config.server.url,
    port: config.server.port,
    online: config.server.online,
    if (config.server.key) {
        https: {
     	    "key": config.server.key,
     	    "cert": config.server.cert
        }
    }
});
```

Here, config.server.key and config.server.cert would be the full path to the local SSL:

```js
https: {
    "key": "/Users/seothemes/.valet/Certificates/example.dev.key",
    "cert": "/Users/seothemes/.valet/Certificates/example.dev.crt"
}
```

**Comment by craigsimps** [comment]
So at the moment, we have a config for `server`, which includes `url`. This URL maps to the `proxy` key within the BrowserSync task. To make things simpler, I'd like to remove this mapping step and just have BrowserSync config entered from within your own Gulpfile.

For example, your Gulpfile.js would include:

```
toolkit.extendConfig({
    /* ... shortened for brevity */
    server: {
        /* BrowserSync config here */
        proxy: "example.dev",
        port: "443",
        https: {
            "key": "/Users/seothemes/.valet/Certificates/example.dev.key",
            "cert": "/Users/seothemes/.valet/Certificates/example.dev.crt"
        }
    }
});
```

And then the task could be simplified to:

```
bs.init({
    config.server
});
```

Some testing is required to make sure this would work, but I think it would make sense. And it means we don't have to do any conditional checks within the BS task when the BS library is capable of carrying all that stuff out natively.

**Comment by seothemes** [comment]
Yeah, I like your way better. I'd submit a PR with the changes but I'm not sure how to go about editing node packages.
