### ISSUE TITLE
Allow CSS Nano Parameters

### ISSUE THREAD

**Issue by cjkoepke** [craigsimps/gulp-wp-toolkit#104]
## Expected Behavior
It would be nice to be able to pass options to the CSS Nano plugin, via something like this:

```js
css: {
	basefontsize: 18,
	remreplace: false,
	remmediaquery: false,
	cssnano: {
		'z-index': false,
	},
}
```

## Current Behavior
You can't pass any options.

## Possible Solution
Pass to the config option (if present) to the `cssnano()` block in the `build:css` file.

## Context
If I need to keep `z-index` levels for plugin compatibility (WooCommerce sets certain things to over 1000), I have to rebuild a custom build pipeline. This is more work than necessary, so at the moment I'm printing `z-index` overwrites into the header as inline styles.

**Comment by cjkoepke** [comment]
Also, happy to submit a PR for this.

**Comment by craigsimps** [comment]
This feature has been added in release (2.3.1)[https://github.com/craigsimps/gulp-wp-toolkit/releases/tag/2.3.1]

Example config available at:
https://github.com/craigsimps/gulp-wp-toolkit/blob/master/example/Gulpfile.js#L84-L89
