### ISSUE TITLE
Root value for pxtorem is set at 16

### ISSUE THREAD

**Issue by craigsimps** [craigsimps/gulp-wp-toolkit#11]
In the CSS build task pixel sizes are converted to rems using `postcss-pxtorem`. The root value for this conversion is set at 16px because at the moment this is the base font size in my starter theme.

However if the base font size in my starter theme is changed (to 18px for example), this results in all other elements becoming oversized because PostCSS Pxtorem is still using 16px as its root value.

Propose creating a config variable within `css` section for base font size allowing the value to be changed on a per theme basis.

**Comment by GaryJones** [comment]
Agreed that this makes sense.
