### ISSUE TITLE
Allow some JS files to be copied without merge

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#18]
The current JS tasks takes an array of files to merge, and concats them before minifying and saving them at the destination. I've got some develop/js files that should either just be moved, or grouped into it's a new concatenated file.

Option 1:
Support a `standalone` flag which allows named files to be minified and copied, but not concatenated with anything else.

Option 2:
Allow `js` task to support multi-dimensional arrays that are then grouped (and named)?:

```
js: {
    [
        files: [
            'develop/js/a.js'
            'develop/js/b.js',
            'develop/js/c.js'
        ],
        filename: 'letters'
    ],
    [
         files: [
            'develop/js/1.js',
            'develop/js/2.js'

        ],
        filename: 'numbers'
    ],
    [
         files: [
            'develop/js/foobar.js',
        ],
        filename: 'standalone'
    ]

},
```

For instance, this would allow `numbers.js` to be conditionally enqueued, while `letters.js` is always enqueued. `standalone.js` would also be enqueable as needed, it just happens to have been concatenated with zero other files before minifying.

**Comment by craigsimps** [comment]
This feature has now been implemented in changeset acf96de.

The `gulp build:js` task now loops through the `config.js` object, so that source JS files can be grouped and named before being run through the Gulp task. There is now no config within `gulp-wp-toolkit` for file names/ files, this should be implemented from within the theme Gulpfile by adding the following section to the extended config:

```
js: {
           'letters' : [
               'develop/js/a.js',
               'develop/js/b.js',
               'develop/js/c.js'
           ],
           'numbers' : [
               'develop/js/1.js',
               'develop/js/2.js'
           ],
           'standalone' : [
               'develop/js/standalone.js'
           ]
       }
```

**Comment by GaryJones** [comment]
Would that produce three minified files, `/js/letters.js`, `/js/numbers.js` and `/js/standalone.js`?

**Comment by craigsimps** [comment]
Yes, three expanded, three minified.

**Comment by GaryJones** [comment]
Great! This should be documented in the readme, or at least setup in your starter theme (which is what I've been using as the default usage example for some bits up until now).

Thanks!
