### ISSUE TITLE
Fix style file headers

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#19]
Right now, the generated style.css file headers are inflexible. `Tags:` and `Domain Path` are missing, and themes would be forced to have a `Template: genesis`, even if the toolkit was used on a non-child theme. The default values in the the toolkits `config.js` are mostly worthless, as not overriding them in the theme's `extendConfig` means that info from the toolkits package.json (i.e. author = Craig Simpson) would be added.

**Comment by GaryJones** [comment]
> Note, that since Author URI and License URI are now supported, the config.theme key for the Theme URI is now `themeuri` instead of `homepage`.

@craigsimps If you feel that backwards compatibility should be maintained, we should be able to add in an extra check that fallsback to `homepage` if `themeuri` is empty.

**Comment by craigsimps** [comment]
I don't think we need to maintain any sort of backward compatibility at this stage.
