### ISSUE TITLE
DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

### ISSUE THREAD

**Issue by craigsimps** [craigsimps/gulp-wp-toolkit#20]
When running any of the build tasks, the error `DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.` is shown.

Investigation has led me to the `formidable` package, which appears in the dependency tree here:

![screen shot 2017-01-25 at 23 28 07](https://cloud.githubusercontent.com/assets/11818429/22313744/11b360fe-e356-11e6-9895-484e1122a4ed.png)

This suggests that version 1.0.17 is in use at the moment. On viewing the repository https://github.com/felixge/node-formidable I have noted that the current version is 1.1.1 and that the latest release 10 days ago mentions 

> Fix DeprecationWarning about os.tmpDir() (Christian)

Further investigation is required to find exactly which package is dependant on `node-formidable` before it can be updated.

**Comment by GaryJones** [comment]
> The packages form-data and connect both have dependencies on node-formidable and request version 1.0.x.

In which case, the author of these packages need requesting to update :/

**Comment by GaryJones** [comment]
The 1.1.1 release of formidable [breaks](https://github.com/form-data/form-data/pull/315) `form-data` so it may be a while until this is fixed.

**Comment by GaryJones** [comment]
I'm not sure if https://github.com/senchalabs/connect is the right one, but if so, that latest release is 3.5.0 and doesn't appear to have a direct dependency on formidable.

[Express](https://github.com/expressjs/express) is at 4.14.1

**Comment by craigsimps** [comment]
Yes, that's the correct package. The dependency on `formidable` is in the `package.json` of `connect` (https://github.com/senchalabs/connect) which is installed as a dependency of `express` (appears to be using version 1.x of `connect`). In my dummy install it's located at `/node_modules/express/node_modules/connect/package.json` and references `"formidable": "1.0.x"`.

**Comment by GaryJones** [comment]
Do you still use `browser-sync`?

It also gives a couple of other warnings of its dependencies:
```
warning gulp-wp-toolkit > browser-sync > browser-sync-ui > weinre > express@2.5.11: express 2.x series is deprecated
warning gulp-wp-toolkit > browser-sync > browser-sync-ui > weinre > express > connect@1.9.2: connect 1.x series is deprecated
```

**Comment by gsc89** [comment]
We all (highrise digital) use this feature as part of our local development process. It just makes it easier than having to manually refresh the page for every code change.

**Comment by GaryJones** [comment]
Understood.

I've not seen the original error for a while. Is it still an issue, or can we close this?

**Comment by craigsimps** [comment]
I'm not seeing the initial error, in fact, I think it was initially only displayed on Mac OS. If you're no longer seeing it @GaryJones then I'm happy to close this out.
