### ISSUE TITLE
lint:colors src is wrong?

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#24]
![screenshot 2017-02-01 10 05 04](https://cloud.githubusercontent.com/assets/88371/22502691/eb869fb2-e865-11e6-9d6d-4d3fed4e3127.png)

I've tried changing the [src](https://github.com/craigsimps/gulp-wp-toolkit/blob/787a829ea53174631e832145fad75a4af137ca21/tasks/lint/colors.js#L12) to various values, but not found the right one yet.

**Comment by craigsimps** [comment]
Untested, but think it should be `config.src.css`.

**Comment by GaryJones** [comment]
I tried that, and didn't have any joy. I wasn't sure why PostCSS was trying to run a tool on `.scss` files.

**Comment by craigsimps** [comment]
Changed to `config.src.css` and got the following results from an empty theme:

![screen shot 2017-02-01 at 10 24 57](https://cloud.githubusercontent.com/assets/11818429/22503244/c6a7f152-e868-11e6-909a-777cd36cce02.png)

However I'm questioning whether my usage is correct. I think the final compiled `style.css` should be the one under scrutiny, not the source SCSS.

**Comment by GaryJones** [comment]
It's a PostCSS task, so looking at the style.css would make most sense.

**Comment by craigsimps** [comment]
Commit c9b1de3 fixed this issue, by changing the source of the task to `config.src.css`, so just wanted to double check that this could be closed with no further work.

To double check that this was working correctly, I ran the task using the current source (`config.src.css`) and then changed the task source to simply `./style.css` - the output report was the same, and both referenced the SCSS partials where the colour collisions take place, see:

![image](https://user-images.githubusercontent.com/11818429/29944472-8a145766-8e95-11e7-95fd-43a482791b06.png)

**Comment by GaryJones** [comment]
All seems good.
