### ISSUE TITLE
Source map file incorrect

### ISSUE THREAD

**Issue by dianekinney** [craigsimps/gulp-wp-toolkit#27]
I changed the folder name of my sass files from `scss` to `sass` and added an override in gulpfile.js `    src: {
        
        css: 'develop/sass/**/*.scss'
       
    },`

However, style.css.map has been off ever since, and I can't figure out where to address this.  I do get the appearance of source mapping, but it points to completely wrong partial and line.

**Comment by GaryJones** [comment]
Any pattern in how it's wrong?

The sourcemap component is initialised [here](https://github.com/craigsimps/gulp-wp-toolkit/blob/master/tasks/build/css.js#L72), but the path you've changed is two lines earlier, so it shouldn't be an issue. The sourcemap file is written a few lines later, after the styles have passed through PostCSS and adding the banner in. Do commenting out either of these two result in correct sourcemap references?

**Comment by craigsimps** [comment]
My initial testing shows that the Sourcemap is only 100% accurate when the PostCSS and Banner tasks are commented out, the path to SCSS is not a factor.

**Comment by GaryJones** [comment]
How about when one or both of the two intermediary stages are not commented out?

Could `sourcemap.init` be initialised later?

**Comment by GaryJones** [comment]
According to [this](https://github.com/postcss/gulp-postcss#source-map-support), PostCSS should support `gulp-sourcemaps`, so it may be the banner task that is throwing it. 

Could the banner be added at a different point, maybe before `init`?

**Comment by GaryJones** [comment]
With PostCSS and Banner tasks commented out, I'm seeing that I'm [out by 2](https://github.com/postcss/postcss/issues/926).

**Comment by GaryJones** [comment]
`gulp-banner` isn't on the [list of packages](https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support) known to support `gulp-sourcemaps`.

We currently run an older version of `gulp-sass` and `gulp-sourcemaps`, so I'm debugging what I think is a related issue, with the aim to bump these and see if this broken sourcemap issue still occurs.

**Comment by GaryJones** [comment]
I fixed the outdated dependencies and virtual task failing issues, but it hasn't fixed the sourcemap issue.

**Comment by GaryJones** [comment]
If we use no PostCSS, and no Banner, and keep the encoding in the .css file:
```
.pipe(sourcemap.init())
        .pipe(sass.sync({
            outputStyle: config.css.outputStyle,
            includePaths: [].concat(bourbon, neat, normalize)
        }))
        .pipe(sourcemap.write())
```

Then it all works fine. Writing to an external file breaks the references.

**Comment by craigsimps** [comment]
The two most recent themes I have developed using `gulp-wp-toolkit` have shown the source maps to be working correctly and referencing the correct files and line numbers. My hunch is that a package has been updated to support source maps, meaning the feature now works as expected.  Can anyone else provide feedback on their recent experience with SCSS & Sourcemaps?

**Comment by GaryJones** [comment]
Not had the chance to get back on this yet, but I am planning to test.

**Comment by GaryJones** [comment]
Confirming that it looks like the sourcemap is working as intended in the `master` branch (`2.0.0`), both with the default (and locally set) `compressed` and locally set `expanded` values for the `outputStyle`.
