### ISSUE TITLE
Pre-commit Hooks

### ISSUE THREAD

**Issue by craigsimps** [craigsimps/gulp-wp-toolkit#4]
https://github.com/therealklanni/git-guppy
https://gist.github.com/therealklanni/9966d215d2b13a9c0e6e

Git hooks would allow the running of lint checks before the commit is accepted - that way, all code could be made to follow pass the checks (or have exclusions added).

**Comment by GaryJones** [comment]
To disable the linter, update the theme's Gulpfile.js with:

```js
toolkit.extendTasks( gulp, { /* gulp task overrides */
	"pre-commit": ''
} );
```

**Comment by GaryJones** [comment]
Currently the `pre-commit` task has been [removed](https://github.com/craigsimps/gulp-wp-toolkit/commit/a6d67ad397cbfa9258913b38665a63928d5881a3) from this repo, but the package dependency kept, so that themes are are at a pre-commit lintable stage can turn it on.

**Comment by GaryJones** [comment]
Once documentation has been added for how to turn this on, this ticket is resolved IMO.

**Comment by GaryJones** [comment]
With the removal from the gulpfile, each new commit throws "Task 'pre-commit' is not in your gulpfile" error, and the only way to get around it is apparently to delete `.git/hooks/pre-commit`. We should do what's needed (default task of empty `pre-commit`?)  to ensure this is resolved.
