### ISSUE TITLE
gulp-bower breaks when bower.json does not exist

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#42]
Bower can be replaced with npm / yarn. As such, dependencies can be listed in `package.json` instead of in a `bower.json`.

Running `gulp build` fails, as in my theme, `bower.json` does not exist. It should probably continue silently if the file is absent.

(Or, strip out `gulp-bower` completely)

![screenshot 2017-07-28 14 32 10](https://user-images.githubusercontent.com/88371/28719351-8f8a1974-73a1-11e7-818b-0bc88ca72eae.png)

**Comment by gsc89** [comment]
I did notice this and I had to put an override in place for dependencies: 

https://github.com/highrisedigital/wpgetstarted/blob/master/content/themes/the-ground-floor/gulpfile.js#L48
