### ISSUE TITLE
Should build:potomo be part of build:i18n?

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#44]
The `build:i18n` process generates the `.pot` file into `develop/languages`, but doesn't try to convert `.po` files in the same directory to `.mo` files in `languages`.

Should it?

Right now `build:potomo` is not part of the default build process at all.

**Comment by craigsimps** [comment]
I wonder if `build:i18n` should be split to run two tasks from it. So it would become something like:

```
'build:i18n': [['build:i18n:potgen', 'build:i18n:potomo']]
```

Which references the two separate tasks of generating a .pot file and converting .po to .po.

**Comment by craigsimps** [comment]
Yes, exactly what I meant. Looking at #50 now.

**Comment by GaryJones** [comment]
PR updated.
