### ISSUE TITLE
Use `const` instead of `var`

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#53]
https://stackoverflow.com/a/21237365/2208553 suggests there may be small performance benefits in using `const` instead of `var`.

For example, in [potomo.js](https://github.com/craigsimps/gulp-wp-toolkit/blob/master/tasks/build/potomo.js):

```js
var gulp = require('gulp'),
    config = require('../../config'),
    potomo = require('gulp-potomo'),
    notify = require('gulp-notify');
```

would become:

```js
const gulp   = require('gulp');
const config = require('../../config');
const potomo = require('gulp-potomo');
const notify = require('gulp-notify');
```

Looks like [support for `const`](http://node.green/#ES2015-bindings-const) goes back to Node 0.10.

**Comment by GaryJones** [comment]
Might only be available in ES6.

**Comment by craigsimps** [comment]
Yes, makes sense to switch if there's a possible performance benefit.
