### ISSUE TITLE
Add minimum node engine version?

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#54]
Should we add a minimum node version [engine](https://docs.npmjs.com/files/package.json#engines) to `package.json`?

Some of our dependencies say they support `>=0.1.0`. We should still be able to use them, but we'd also be able to use some ES2015 features, as per [node.green](http://node.green/). See #53.

**Comment by GaryJones** [comment]
FWIW, [this](https://github.com/sindresorhus/gulp-changed/commit/b2aa51fecd244de09881b90076f0ccf244f0a1cc) is one example of some of the ES2015 changes. In some ways, it seems like changes for the sake of changes, but if it optimises things under the hood, and uses what will become more prevalent standard syntax, then I'm for it.

**Comment by GaryJones** [comment]
[Node.js Long-term Support Working Group](https://github.com/nodejs/LTS/blob/master/README.md).

**Comment by craigsimps** [comment]
Happy to go with 6.

**Comment by GaryJones** [comment]
Closed with 3e73655a254bcc6ffe91ae6997fce9113c03719f.
