### ISSUE TITLE
Improve stylesheet log messages

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#57]
![screenshot 2017-08-22 09 45 53](https://user-images.githubusercontent.com/88371/29556830-f98d0ce2-871e-11e7-90b9-641404c4d5aa.png)

In my example, it's compiling and saving `style.css`, `style.css.map`, `editor-style.css` and `editor-style.css.map`, but the log messages don't reflect that in a useful way. 

It would be nice to see if the generated file name could be placed into the log messages.

**Comment by craigsimps** [comment]
Agreed, and the same should apply for the JS tasks. This ties in with #56 so I think it would make sense to review and overhaul the notifications/ logging of task completion in general, giving more verbose success/ failure message.

**Comment by craigsimps** [comment]
A quick win before the 1.3.0 release though would be to simply append the filename to the notification message.
