### ISSUE TITLE
Not using browserslist?

### ISSUE THREAD

**Issue by keithdevon** [craigsimps/gulp-wp-toolkit#74]
Not exactly a bug, but I've recently had an issue where the appropriate prefixes aren't added for iOS version 8.

I believe this is because `autoprefix()` is being used with the default settings, which only looks for the last two versions of a browser.

Looking into it, it looks like the best practice is to use `browserslist` in `package.json`. Is this possible with this toolkit?

**Comment by GaryJones** [comment]
Good catch. Be it a `browserlist` file, or a config string value that can set, we should allow autoprefix to be told which browsers to cater for.

**Comment by craigsimps** [comment]
Out of the box the default Autoprefixer settings are used, which are `> 1%, last 2 versions, Firefox ESR`.

You can override these by adding browserslist config in one of a number of places, the most common of these being the `package.json` file in your theme. I've been carrying out some tests this morning using the following piece of CSS:

```
.site-container {
	display: inline-flex;
	align-self: flex-start;
}
```

When I compile SCSS to CSS with the default settings, I see:

```
.site-container {
  display: -webkit-inline-box;
  display: -ms-inline-flexbox;
  display: inline-flex;
  -ms-flex-item-align: start;
      align-self: flex-start;
}
```

If I wanted to also support an older browser, for example iOS 8 and greater, I can do so by adding the following to my `package.json`.

```
"browserslist": "iOS >= 8, >1%, last 2 versions"
```

Which gives me the following compiled output:

```
.site-container {
  display: -webkit-inline-box;
  display: -webkit-inline-flex;
  display: -ms-inline-flexbox;
  display: inline-flex;
  -webkit-align-self: flex-start;
      -ms-flex-item-align: start;
          align-self: flex-start;
}
```

Using one of the other means of configuration, I could drop the `browserslist` key from my `package.json` file and instead place a file name `browserslist` in the theme root. Placing my updated browserslist config in this `browserlist` file gives the same output.

**Comment by GaryJones** [comment]
We probably just need this documented somewhere then.

**Comment by craigsimps** [comment]
Agree, might be worth using the Wiki and documenting the various tasks and their overrides.
