### ISSUE TITLE
Update README and example

### ISSUE THREAD

**Issue by timothyjensen** [craigsimps/gulp-wp-toolkit#80]
I want to bring up some minor things that I noticed while reading through the docs yesterday.

From the README:
```
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-wp-toolkit": "^1.0.1"
  }
```
The version for `gulp-wp-toolkit` should probably be "^2" so that new users jump into using version 2 right away.

Also, the line below should be all lower case (`basefontsize`) or else the value will not be recognized.
https://github.com/craigsimps/gulp-wp-toolkit/blob/6a3a36c1e1f3651f58643b5433cbf85f6d4fe5c5/example/Gulpfile.js#L82

**Comment by craigsimps** [comment]
Fixed these issues within https://github.com/craigsimps/gulp-wp-toolkit/commit/c954ca9949ad69125aa3552536ebf07d5a12b19c -- they are in the 2.1.0 release version.
