### ISSUE TITLE
Bump task does not respect arguments

### ISSUE THREAD

**Issue by timothyjensen** [craigsimps/gulp-wp-toolkit#87]
## Expected Behavior
Running the command `gulp bump --minor` should bump version 1.0.0 to 1.1.0.

## Current Behavior
Running the command `gulp bump --minor` or `gulp bump --major` bumps version 1.0.0 to 1.0.1.

## Your Environment
- Version used: 2.1.0
- Node version: 8.9.1
- NPM version: 5.6
- Theme: starter theme

**Comment by timothyjensen** [comment]
The simplest fix is to run the command as `gulp bump --type=minor` instead of the simplified `gulp bump --minor`, although I prefer the latter because it's fewer characters.

One way to fix this bug is to change `type` to a variable and then assign it a value like so:
```js
if ( args.hasOwnProperty('major') ) {
  type = 'major';
} else if ( args.hasOwnProperty('minor') ) {
  type = 'minor';
} else {
  type = 'patch';
}
```

**Comment by blogjunkie** [comment]
Hi @craigsimps I'm still getting this bug on gulp-wp-toolkit v 2.3.2

```
$ gulp bump --major
[10:56:10] Using gulpfile ~/Sites/soyacincau/app/public/wp-content/themes/soyacincau/gulpfile.js
[10:56:10] Starting 'bump'...
[10:56:10] Bumped 1.0.2 to 1.0.3 with type: patch
[10:56:10] Finished 'bump' after 80 ms
$ gulp bump --type=major
[10:57:19] Using gulpfile ~/Sites/soyacincau/app/public/wp-content/themes/soyacincau/gulpfile.js
[10:57:19] Starting 'bump'...
[10:57:19] Bumped 1.0.3 to 1.0.4 with type: patch
[10:57:19] Finished 'bump' after 80 ms
```

I tried to update gulp-wp-toolkit to the latest version but npm tells me that 2.3.2 is the latest version

```
$ npm search gulp-wp-toolkit
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | VERSION  | KEYWORDS
gulp-wp-toolkit           | Set of configurable… | =craigsimps     | 2018-06-05 | 2.3.2    |         
```

Not sure what to do next, can you please advise. Thank you
