### ISSUE TITLE
Remove JSCS

### ISSUE THREAD

**Issue by GaryJones** [craigsimps/gulp-wp-toolkit#9]
[JSCS is now end of life](http://eslint.org/blog/2016/07/jscs-end-of-life), and with #2 having implemented ESLint, there should be no reason to continue to include JSCS. 

Removing it sooner, and bumping the major version number to indicate breaking compatibility, is likely to be far less painful than doing it later.

**Comment by craigsimps** [comment]
Yes, I would agree. With ESLint in place and using the shared WP config (as in #2), it can be removed.

**Comment by craigsimps** [comment]
Closing this issue, JSCS was removed in commit 3a12406
