### ISSUE TITLE
Consider adding CSSComb to automatically format stylesheet

### ISSUE THREAD

**Issue by seothemes** [craigsimps/gulp-wp-toolkit#93]
Link - https://github.com/csscomb/csscomb.js

There would need to be a conditional to limit it to the unminifed stylesheet only.

Here's how I'm currently using it - [example](https://github.com/seothemes/genesis-starter/blob/2.6.0/gulpfile.js#L158).

WPCS config:

```json
{
    "remove-empty-rulesets": true,
    "always-semicolon": true,
    "color-case": "lower",
    "block-indent": "\t",
    "color-shorthand": false,
    "element-case": "lower",
    "eof-newline": true,
    "leading-zero": true,
    "quotes": "single",
    "space-before-colon": "",
    "space-after-colon": " ",
    "space-before-combinator": " ",
    "space-after-combinator": " ",
    "space-between-declarations": "\n",
    "space-before-opening-brace": " ",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": "\n",
    "space-before-selector-delimiter": "",
    "space-before-closing-brace": "\n",
    "strip-spaces": true,
    "unitless-zero": true,
    "vendor-prefix-align": true
}
```

**Comment by craigsimps** [comment]
Yes, seems like something which could be included in the default `build:css` task as long as the stylesheet is outputting in expanded style. The WPCS config could also be stored within the toolkit as with `.eslintrc`, `.stylelintrc` etc with an optional override if the file exists in the theme root.

Might be good to use the PostCSS version, and do something like:

```
    if ('expanded' === outputConfig.outputStyle) {
      postProcessors.push(csscomb( /path/to/custom/config ));
    }
```

https://www.npmjs.com/package/postcss-csscomb

**Comment by seothemes** [comment]
Awesome, I'll get started on this.

**Comment by seothemes** [comment]
Working on this here https://github.com/seothemes/gulp-wp-toolkit/tree/csscomb

Not really sure how to go about testing this so any feedback would be much appreciated!

**Comment by craigsimps** [comment]
@seothemes what is the source of the `.csscomb.json` file that you pasted above? Some of the rules seem to conflict with the `stylelint-config-wordpress` package which is used for linting. 

For example, the ruleset above converts string quotes to single, but the Stylelint config is looking for double.

**Comment by seothemes** [comment]
I'm not sure to be honest, it was a while ago. Single quotes aren't right so it may need to be double checked. I just did a search and found this old gist which appears to be what's needed https://github.com/cedaro/grunt-wp-css/blob/develop/tasks/config/default.json

**Comment by seothemes** [comment]
BTW, thanks for adding this so quickly! Really nice work. Going to switch all themes over to this now (and give credit of course). Much cleaner than using the big old Gulp file.
